In [0]:
%sql
show tables

database,tableName,isTemporary
default,loan_analysiss,false

In [0]:
%sql
select * from loan_analysiss

Customer_ID,Age,Gender,Occupation,Marital Status,Family Size,Income,Expenditure,Use Frequency,Loan Category,Debt,Overdue,Loan,Returned Cheque,Dishonour of Bill
IB14001,30,MALE,BANK MANAGER,SINGLE,4,50000,22199,6,HOUSING,"428,980",5,50000,6,9
IB14008,44,MALE,PROFESSOR,MARRIED,6,51000,19999,4,SHOPPING,"428,980",3,51000,1,5
IB14012,30,FEMALE,DENTIST,SINGLE,3,58450,27675,5,TRAVELLING,"428,980",6,58450,3,1
IB14018,29,MALE,TEACHER,MARRIED,5,45767,12787,3,GOLD LOAN,"13,000",7,45767,0,4
IB14022,34,MALE,POLICE,SINGLE,4,43521,11999,3,AUTOMOBILE,"13,000",2,43521,1,2
IB14024,55,FEMALE,NURSE,MARRIED,6,34999,19888,4,AUTOMOBILE,"33,333",1,34999,0,3
IB14025,39,FEMALE,TEACHER,MARRIED,6,46619,18675,4,HOUSING,"33,333",8,46619,6,8
IB14027,51,MALE,SYSTEM MANAGER,MARRIED,3,49999,19111,5,RESTAURANTS,"33,333",8,49999,2,5
IB14029,24,FEMALE,TEACHER,SINGLE,3,45008,17454,4,AUTOMOBILE,"33,333",9,45008,4,7
IB14031,37,FEMALE,SOFTWARE ENGINEER,MARRIED,5,55999,23999,5,AUTOMOBILE,"33,333",2,55999,5,3
IB14032,24,MALE,DATA ANALYST,SINGLE,4,60111,28999,6,AUTOMOBILE,"33,333",5,60111,1,2
IB14034,32,MALE,PRODUCT ENGINEER,MARRIED,6,null,29000,7,COMPUTER SOFTWARES,"33,333",6,null,5,4
IB14037,54,FEMALE,TEACHER,MARRIED,5,48099,19999,4,RESTAURANTS,"33,333",1,48099,7,5
IB14039,45,MALE,ACCOUNT MANAGER,MARRIED,7,45777,18452,4,GOLD LOAN,"33,333",7,45777,8,1
IB14041,59,FEMALE,ASSISTANT PROFESSOR,MARRIED,4,50999,22999,5,EDUCATIONAL LOAN,"33,333",3,50999,9,9
IB14042,25,FEMALE,DOCTOR,SINGLE,4,60111,27111,5,TRAVELLING,"33,333",4,60111,1,0
IB14045,31,MALE,STORE KEEPER,SINGLE,5,40999,11999,3,BOOK STORES,"210,000",1,40999,0,1
IB14049,49,MALE,BANK MANAGER,MARRIED,4,45999,14500,4,TRAVELLING,"21,000",4,45999,7,3
IB14050,56,MALE,CIVIL ENGINEER,MARRIED,4,null,13999,3,HOUSING,"21,000",6,null,4,2
IB14054,58,FEMALE,DOCTOR,MARRIED,5,60000,25000,5,HOUSING,"21,000",5,60000,9,0
IB14057,25,MALE,AIRPORT OFFICER,SINGLE,4,40000,18888,3,RESTAURANTS,"21,000",8,40000,1,7
IB14060,36,FEMALE,CLERK,MARRIED,4,35000,15000,3,HOUSING,"21,000",2,35000,4,8
IB14070,40,MALE,PUBLIC WORKS,MARRIED,4,38000,20000,3,GOLD LOAN,"21,000",9,38000,3,2
IB14078,45,FEMALE,FIRE DEPARTMENT,MARRIED,4,40000,18888,4,AUTOMOBILE,"21,000",1,40000,2,1
IB14079,25,MALE,CLERK,SINGLE,3,35000,9000,2,GOLD LOAN,"21,000",3,35000,1,2
IB14082,60,FEMALE,TEACHER,MARRIED,5,70000,40000,9,GOLD LOAN,"21,000",4,70000,4,3
IB14085,30,MALE,ELECTRICIAN,MARRIED,4,30000,15000,5,HOUSING,"21,000",5,30000,5,5
IB14086,51,FEMALE,TECHNICIAN,MARRIED,5,30000,null,5,RESTAURANTS,"21,000",7,30000,4,10
IB14089,25,MALE,PROFESSOR,SINGLE,5,62145,31254,4,BOOK STORES,"21,000",6,62145,6,5
IB14092,47,MALE,SYSTEM ENGINEER,MARRIED,4,52364,45612,3,GOLD LOAN,"21,000",4,52364,5,4
1B14093,21,FEMALE,MANAGER,SINGLE,3,42516,24567,7,AUTOMOBILE,"21,000",8,42516,2,3
1B14094,49,MALE,ASSISTANT PROFESSOR,MARRIED,5,65214,42589,5,HOUSING,"21,000",5,65214,1,2
IB14096,33,FEMALE,CLERK,MARRIED,3,35684,15247,3,RESTAURANTS,"21,000",3,35684,3,2
IB14099,47,FEMALE,DOCTOR,MARRIED,4,72154,45286,4,AUTOMOBILE,"21,000",2,72154,5,2
IB14101,33,FEMALE,PRODUCT ENGINEER,MARRIED,5,null,45812,5,AUTOMOBILE,"21,000",4,null,6,3
IB14104,54,MALE,AIRPORT OFFICER,MARRIED,6,80000,32541,2,AUTOMOBILE,"21,000",1,80000,2,3
IB14106,29,MALE,FIRE DEPARTMENT,MARRIED,5,45213,32457,9,TRAVELLING,"21,000",7,45213,2,5
IB14107,44,FEMALE,ACCOUNT MANAGER,MARRIED,4,800000,15632,8,AUTOMOBILE,"21,000",5,800000,3,4
IB14109,56,MALE,DRIVER,MARRIED,5,30000,15426,7,TRAVELLING,"21,000",6,30000,4,6
IB14111,57,FEMALE,CORPORATE OFFICER,MARRIED,3,52143,null,4,COMPUTER SOFTWARES,"21,000",4,52143,3,2
IB14113,49,MALE,ASSISTANT MANAGER,MARRIED,7,45612,39542,3,SHOPPING,"21,000",7,45612,3,2
IB14115,41,MALE,BANK MANAGER,MARRIED,6,64125,21246,6,TRAVELLING,"21,000",5,64125,3,3
IB14117,39,FEMALE,SYSTEM OFFICER,MARRIED,6,null,32541,5,EDUCATIONAL LOAN,"21,000",3,null,4,4
IB14120,47,FEMALE,TEACHER,MARRIED,3,50000,42563,4,RESTAURANTS,"21,000",6,50000,2,3
IB14121,33,MALE,DOCTOR,MARRIED,6,70000,12541,8,HOUSING,"21,000",4,70000,1,3
IB14123,36,MALE,ELECTRICIAN,MARRIED,2,36985,25648,6,AUTOMOBILE,"21,000",7,36985,5,3
IB14125,29,FEMALE,TEACHER,MARRIED,4,59999,42568,4,AUTOMOBILE,"21,000",5,59999,2,2
IB14126,57,MALE,FIRE DEPARTMENT,MARRIED,5,54123,null,7,RESTAURANTS,"21,000",6,54123,2,1
IB14128,46,FEMALE,CLERK,MARRIED,3,750000,25641,5,GOLD LOAN,"21,000",4,750000,3,4
IB14130,43,MALE,PRODUCT ENGINEER,MARRIED,4,50147,45863,8,COMPUTER SOFTWARES,"21,000",8,50147,3,5
IB14134,33,MALE,DOCTOR,MARRIED,6,70000,33541,8,BUILDING,"21,000",4,70000,1,3
IB14136,36,MALE,ELECTRICIAN,MARRIED,2,36985,25648,6,ELECTRONICS,"21,000",7,36985,5,3
IB14138,27,FEMALE,SOFTWARE ENGINEER,SINGLE,4,40000,22000,4,GOLD LOAN,"21,000",4,40000,5,3
IB14140,45,MALE,BANK MANAGER,MARRIED,6,55670,32500,5,TRAVELLING,"21,000",3,55670,4,4
IB14143,34,FEMALE,TEACHER,MARRIED,4,45389,null,5,HOME APPLIANCES,"21,000",4,45389,4,3
IB14145,45,FEMALE,CLERK,MARRIED,5,40560,38789,6,TRAVELLING,"21,000",6,40560,6,7
IB14146,56,MALE,FIRE DEPARTMENT,MARRIED,6,67890,34567,5,TRAVELLING,"21,000",5,67890,3,4
IBI4148,46,MALE,SYSTEM OFFICER,MARRIED,5,56780,24560,5,GOLD LOAN,"21,000",6,56780,6,4
IBI4150,38,FEMALE,ACCOUNT MANAGER,MARRIED,4,45600,19870,4,HOME APPLIANCES,"21,000",5,45600,5,4
IBI4153,58,MALE,SYSTEM ENGINEER,MARRIED,6,76800,null,5,TRAVELLING,"21,000",6,76800,5,3
IBI4155,24,FEMALE,SOFTWARE ENGINEER,SINGLE,4,55680,29000,5,AUTOMOBILE,"21,000",5,55680,6,4
IBI4157,35,MALE,BANK MANAGER,MARRIED,4,930000,35680,6,HOUSING,"21,000",5,930000,5,5
IB14158,54,MALE,AIRPORT OFFICER,MARRIED,6,80000,62541,2,AUTOMOBILE,"21,000",1,80000,2,3
IB14160,29,MALE,FIRE DEPARTMENT,MARRIED,5,45213,32457,9,TRAVELLING,"21,000",7,45213,2,5
IB14163,44,FEMALE,ACCOUNT MANAGER,MARRIED,4,800000,15632,8,COMPUTER SOFTWARES,"21,000",5,800000,3,4
IB14164,56,MALE,DRIVER,MARRIED,5,30000,15426,7,TRAVELLING,"21,000",6,30000,4,6
IB14167,57,FEMALE,CORPORATE OFFICER,MARRIED,3,52143,null,4,AUTOMOBILE,"21,000",4,52143,3,2
IB14169,49,MALE,ASSISTANT MANAGER,MARRIED,7,45612,39542,3,SHOPPING,"21,000",7,45612,3,2
IB14171,47,FEMALE,DOCTOR,MARRIED,4,72154,45286,4,AUTOMOBILE,"21,000",2,72154,5,2
IB14173,33,FEMALE,PRODUCT ENGINEER,MARRIED,5,null,45812,5,SHOPPING,"210,000",4,null,6,3
IB14176,54,MALE,AIRPORT OFFICER,MARRIED,6,80000,62541,2,HOUSING,"210,000",1,80000,2,3
IB14178,51,MALE,SYSTEM MANAGER,MARRIED,3,49999,19111,5,ELECTRONICS,"210,000",8,49999,2,5
IB14179,24,FEMALE,TEACHER,SINGLE,3,45008,17454,4,AUTOMOBILE,"210,000",9,45008,4,7
IB14181,37,FEMALE,SOFTWARE ENGINEER,MARRIED,5,55999,23999,5,HOME APPLIANCES,"210,000",2,55999,5,3
IB14184,24,MALE,DATA ANALYST,SINGLE,4,60111,28999,6,RESTAURANTS,"210,000",5,60111,1,2
IB14186,44,MALE,PROFESSOR,MARRIED,6,59000,19999,4,AUTOMOBILE,"210,000",3,59000,1,5
IB14187,30,FEMALE,DENTIST,SINGLE,3,58450,27675,5,TRAVELLING,"210,000",6,58450,3,1
IB14189,29,MALE,TEACHER,MARRIED,5,45767,12787,3,GOLD LOAN,"210,000",7,45767,0,4
IB14191,34,MALE,POLICE,SINGLE,4,44521,11999,3,AUTOMOBILE,"210,000",2,44521,1,2
IB14194,55,FEMALE,NURSE,MARRIED,6,34999,19888,4,TRAVELLING,"210,000",1,34999,0,3
IB14195,32,MALE,PRODUCT ENGINEER,MARRIED,6,null,29000,7,SHOPPING,"210,000",6,null,5,4
IB14197,54,FEMALE,TEACHER,MARRIED,5,48099,19999,4,RESTAURANTS,"210,000",1,48099,7,5
IB14199,45,MALE,ACCOUNT MANAGER,MARRIED,7,45777,18452,4,GOLD LOAN,"210,000",7,45777,8,1
IB14201,59,FEMALE,ASSISTANT PROFESSOR,MARRIED,4,60999,22999,5,AUTOMOBILE,"210,000",3,60999,9,9
IBI4202,35,MALE,BANK MANAGER,MARRIED,4,67500,25780,6,AUTOMOBILE,"210,000",5,67500,5,5
IB14204,54,MALE,AIRPORT OFFICER,MARRIED,6,81000,62541,2,DINNING,"210,000",1,81000,2,3
IB14206,51,MALE,SYSTEM MANAGER,MARRIED,3,39999,19111,5,AUTOMOBILE,"210,000",8,39999,2,5
IB14208,36,FEMALE,CLERK,MARRIED,4,45300,15000,3,HOUSING,"210,000",2,45300,4,8
IB14210,40,MALE,PUBLIC WORKS,MARRIED,4,38000,20000,3,GOLD LOAN,"210,000",9,38000,3,2
IB14213,31,MALE,STORE KEEPER,SINGLE,5,40999,11999,3,AUTOMOBILE,"210,000",1,40999,0,1
IB14215,49,MALE,BANK MANAGER,MARRIED,4,45999,14500,4,TRAVELLING,"210,000",4,45999,7,3
IB14216,24,MALE,DATA ANALYST,SINGLE,4,60111,28999,6,RESTAURANTS,"210,000",5,60111,1,2
IB14218,44,MALE,PROFESSOR,MARRIED,6,51000,19999,4,SHOPPING,"210,000",3,51000,1,5
IB14220,30,FEMALE,DENTIST,SINGLE,3,58450,27675,5,TRAVELLING,"210,000",6,58450,3,1
IB14221,31,MALE,STORE KEEPER,SINGLE,5,40999,11999,3,BOOK STORES,"210,000",1,40999,0,1
IB14224,49,MALE,BANK MANAGER,MARRIED,4,45999,14500,4,HOME APPLIANCES,"210,000",4,45999,7,3
IB14225,56,MALE,CIVIL ENGINEER,MARRIED,4,null,13999,3,HOUSING,"210,000",6,null,4,2
IB14227,54,MALE,AIRPORT OFFICER,MARRIED,6,80000,62541,2,HOUSING,"210,000",1,80000,2,3
IB14229,51,MALE,SYSTEM MANAGER,MARRIED,3,49999,19111,5,ELECTRONICS,"210,000",8,49999,2,5
IB14231,24,FEMALE,TEACHER,SINGLE,3,45008,17454,4,AUTOMOBILE,"210,000",9,45008,4,7
IB14233,32,MALE,PRODUCT ENGINEER,MARRIED,6,null,29000,7,AUTOMOBILE,"210,000",6,null,5,4
IB14235,54,FEMALE,TEACHER,MARRIED,5,48099,19999,4,RESTAURANTS,"210,000",1,48099,7,5
IB14236,45,MALE,ACCOUNT MANAGER,MARRIED,7,45777,18452,4,GOLD LOAN,"210,000",7,45777,8,1
IB14238,59,FEMALE,ASSISTANT PROFESSOR,MARRIED,4,50999,22999,5,EDUCATIONAL LOAN,"210,000",3,50999,9,9
IB14239,29,MALE,TEACHER,MARRIED,5,45767,12787,3,GOLD LOAN,"210,000",7,45767,0,4
IB14240,34,MALE,POLICE,SINGLE,4,43521,11999,3,AUTOMOBILE,"210,000",2,43521,1,2
IB14242,55,FEMALE,NURSE,MARRIED,6,34999,19888,4,SHOPPING,"210,000",1,34999,0,3
IB14244,32,MALE,PRODUCT ENGINEER,MARRIED,6,null,29000,7,COMPUTER SOFTWARES,"210,000",6,null,5,4
IB14245,54,FEMALE,TEACHER,MARRIED,5,48099,19999,4,RESTAURANTS,"210,000",1,48099,7,5
IB14247,29,MALE,FIRE DEPARTMENT,MARRIED,5,45213,32457,9,TRAVELLING,"210,000",7,45213,2,5
IB14249,44,FEMALE,ACCOUNT MANAGER,MARRIED,4,700000,15632,8,COMPUTER SOFTWARES,"210,000",5,700000,3,4
IB14251,56,MALE,DRIVER,MARRIED,5,30000,15426,7,GOLD LOAN,"210,000",6,30000,4,6
IB14253,54,MALE,AIRPORT OFFICER,MARRIED,6,80000,42541,2,HOUSING,"210,000",1,80000,2,3
IB14254,29,MALE,FIRE DEPARTMENT,MARRIED,5,43213,22457,9,TRAVELLING,"210,000",7,43213,2,5
IB14256,44,FEMALE,ACCOUNT MANAGER,MARRIED,4,800000,15632,8,COMPUTER SOFTWARES,"210,000",5,800000,3,4
IB14258,29,MALE,TEACHER,MARRIED,5,45767,12787,3,GOLD LOAN,"210,000",7,45767,0,4
IB14260,34,MALE,POLICE,SINGLE,4,43521,11999,3,AUTOMOBILE,"210,000",2,43521,1,2
IB14261,55,FEMALE,NURSE,MARRIED,6,34999,19888,4,SHOPPING,"210,000",1,34999,0,3
IB14263,32,MALE,PRODUCT ENGINEER,MARRIED,6,null,29000,7,COMPUTER SOFTWARES,"210,000",6,null,5,4
IB14265,54,FEMALE,TEACHER,MARRIED,5,48099,19999,4,RESTAURANTS,"210,000",1,48099,7,5
IB14267,55,FEMALE,ASSISTANT PROFESSOR,MARRIED,6,34999,19888,4,SHOPPING,"210,000",1,34999,0,3
IB14269,32,MALE,SOFTWARE ENGINEER,MARRIED,6,null,29000,7,COMPUTER SOFTWARES,"210,000",6,null,5,4
IB14270,54,FEMALE,TEACHER,MARRIED,5,48099,19999,4,RESTAURANTS,"210,000",1,48099,7,5
IB14272,43,MALE,PRODUCT ENGINEER,MARRIED,4,50147,45863,8,COMPUTER SOFTWARES,"210,000",8,50147,3,5
IB14273,33,MALE,DOCTOR,MARRIED,6,70000,41541,8,BUILDING,"210,000",4,70000,1,3
IB14275,36,MALE,ELECTRICIAN,MARRIED,2,36985,25648,6,ELECTRONICS,"210,000",7,36985,5,3
IB14277,49,MALE,ASSISTANT MANAGER,MARRIED,7,45612,39542,3,SHOPPING,"210,000",7,45612,3,2
IB14278,41,MALE,BANK MANAGER,MARRIED,6,64125,51246,6,TRAVELLING,"210,000",5,64125,3,3
IB14280,39,FEMALE,SYSTEM OFFICER,MARRIED,6,null,32541,5,EDUCATIONAL LOAN,"210,000",3,null,4,4
IB14282,51,MALE,SYSTEM MANAGER,MARRIED,3,49999,19111,5,ELECTRONICS,"210,000",8,49999,2,5
IB14283,36,FEMALE,CLERK,MARRIED,4,35000,15000,3,HOUSING,"210,000",2,35000,4,8
IB14285,40,MALE,PUBLIC WORKS,MARRIED,4,38000,20000,3,GOLD LOAN,"210,000",9,38000,3,2
IB14287,31,MALE,STORE KEEPER,SINGLE,5,40999,11999,3,BOOK STORES,"210,000",1,40999,0,1
IB14288,49,MALE,BANK MANAGER,MARRIED,4,45999,14500,4,TRAVELLING,"210,000",4,45999,7,3
IB14289,55,FEMALE,NURSE,MARRIED,6,34999,19888,4,HOUSING,"210,000",1,34999,0,3
IB14291,32,MALE,PRODUCT ENGINEER,MARRIED,6,null,29000,7,SHOPPING,"210,000",6,null,5,4
IB14293,54,FEMALE,TEACHER,MARRIED,5,48099,19999,4,TRAVELLING,"210,000",1,48099,7,5
IBI4294,24,FEMALE,SOFTWARE ENGINEER,SINGLE,4,49680,25000,5,GOLD LOAN,"210,000",5,49680,6,4
IBI4296,35,MALE,BANK MANAGER,MARRIED,4,75250,29865,6,RESTAURANTS,"210,000",5,75250,5,5
IB14299,54,MALE,AIRPORT OFFICER,MARRIED,6,80000,39541,2,HOUSING,"210,000",1,80000,2,3
IB14301,29,MALE,TEACHER,MARRIED,5,45767,12787,3,GOLD LOAN,"210,000",7,45767,0,4
IB14303,56,MALE,CIVIL ENGINEER,MARRIED,4,null,13999,3,HOUSING,"210,000",6,null,4,2
IB14304,30,MALE,ELECTRICIAN,MARRIED,4,30000,15000,5,HOUSING,"210,000",5,30000,5,5
IB14306,51,FEMALE,TECHNICIAN,MARRIED,5,30000,null,5,AUTOMOBILE,"210,000",7,30000,4,10
IB14309,25,MALE,PROFESSOR,SINGLE,5,62145,31254,4,AUTOMOBILE,"210,000",6,62145,6,5
IB14311,47,MALE,SYSTEM ENGINEER,MARRIED,4,52364,45612,3,GOLD LOAN,"210,000",4,52364,5,4
1B14312,21,FEMALE,MANAGER,SINGLE,3,42516,24567,7,EDUCATIONAL LOAN,"210,000",8,42516,2,3
1B14315,49,MALE,ASSISTANT PROFESSOR,MARRIED,5,65214,42589,5,HOUSING,"210,000",5,65214,1,2
IB14317,26,FEMALE,TEACHER,SINGLE,3,45008,17454,4,AUTOMOBILE,"210,000",9,45008,4,7
IB14318,45,FEMALE,ASSISTANT PROFESSOR,MARRIED,6,52361,34154,6,AUTOMOBILE,"210,000",7,52361,2,9
IB14320,29,MALE,SOFTWARE ENGINEER,MARRIED,2,38170,19224,5,SHOPPING,"210,000",2,38170,5,7
IB14321,28,MALE,TEACHER,MARRIED,7,31747,17995,8,COMPUTER SOFTWARES,"210,000",8,31747,1,7
IB14324,52,MALE,PRODUCT ENGINEER,MARRIED,6,74044,16278,5,RESTAURANTS,"210,000",5,74044,9,2
IB14326,37,MALE,DOCTOR,SINGLE,2,56856,23678,7,TRAVELLING,"210,000",8,56856,4,3
IB14327,44,MALE,ELECTRICIAN,MARRIED,5,67214,20246,6,COMPUTER SOFTWARES,"210,000",5,67214,5,3
IB14329,54,FEMALE,ASSISTANT MANAGER,MARRIED,5,59392,25605,8,GOLD LOAN,"210,000",6,59392,7,9
IB14331,29,MALE,BANK MANAGER,MARRIED,5,null,19326,6,DINNING,"210,000",4,null,4,1
IB14333,48,FEMALE,DATA ANALYST,MARRIED,4,57097,16144,6,TRAVELLING,"210,000",4,57097,8,1
IB14336,51,MALE,PROFESSOR,MARRIED,4,69401,28234,6,SHOPPING,"210,000",2,69401,8,4
IB14337,51,FEMALE,DENTIST,MARRIED,7,58465,null,8,AUTOMOBILE,"210,000",5,58465,4,9
IB14339,50,MALE,STORE KEEPER,MARRIED,6,35918,19202,5,SHOPPING,"210,000",1,35918,9,4
IB14340,55,MALE,BANK MANAGER,MARRIED,7,51346,21710,4,DINNING,"210,000",7,51346,1,9
IB14342,29,FEMALE,CIVIL ENGINEER,MARRIED,6,75415,29047,8,ELECTRONICS,"210,000",2,75415,9,1
IB14344,43,MALE,AIRPORT OFFICER,MARRIED,7,null,28032,8,HOUSING,"210,000",7,null,0,4
IB14346,44,FEMALE,TEACHER,MARRIED,2,63953,18376,4,RESTAURANTS,"210,000",4,63953,9,4
IB14349,46,MALE,DOCTOR,MARRIED,3,53852,28974,6,BOOK STORES,"210,000",7,53852,4,5
IB14352,32,FEMALE,ELECTRICIAN,MARRIED,5,70449,null,8,GOLD LOAN,"210,000",7,70449,0,6
IB14354,42,MALE,TEACHER,MARRIED,3,57578,23000,8,EDUCATIONAL LOAN,"210,000",3,57578,8,4
IB14357,45,MALE,FIRE DEPARTMENT,MARRIED,2,77805,16699,5,HOUSING,"210,000",3,77805,2,2
IB14359,46,MALE,CLERK,MARRIED,5,54529,27102,4,COMPUTER SOFTWARES,"210,000",7,54529,7,3
IB14361,37,FEMALE,PRODUCT ENGINEER,SINGLE,6,null,28140,5,AUTOMOBILE,"210,000",8,null,6,8
IB14363,37,MALE,DOCTOR,MARRIED,3,32753,26219,5,SHOPPING,"210,000",7,32753,0,3
IB14365,25,MALE,CIVIL ENGINEER,MARRIED,7,46880,18559,8,DINNING,"210,000",5,46880,5,8
IB14369,37,FEMALE,DOCTOR,MARRIED,5,57453,null,6,TRAVELLING,"210,000",1,57453,9,8
IB14371,53,MALE,AIRPORT OFFICER,MARRIED,5,73093,19194,7,COMPUTER SOFTWARES,"210,000",7,73093,8,0
IB14373,31,MALE,CLERK,MARRIED,4,32714,23632,6,GOLD LOAN,"210,000",1,32714,0,0
IB14375,53,FEMALE,PUBLIC WORKS,MARRIED,6,41645,25095,8,COMPUTER SOFTWARES,"210,000",8,41645,8,2
IB14377,54,MALE,FIRE DEPARTMENT,MARRIED,2,80000,25318,8,SHOPPING,"210,000",1,80000,7,6
IB14378,24,FEMALE,CLERK,MARRIED,3,47361,19718,8,TRAVELLING,"210,000",4,47361,2,1
IB14380,41,FEMALE,NURSE,MARRIED,5,36784,null,4,HOUSING,"210,000",9,36784,3,1
IB14383,56,MALE,PRODUCT ENGINEER,MARRIED,5,44130,27092,8,SHOPPING,"210,000",1,44130,9,0
IB14384,25,MALE,TEACHER,MARRIED,7,64528,21231,5,TRAVELLING,"210,000",1,64528,5,3
IB14387,26,MALE,SOFTWARE ENGINEER,MARRIED,4,43587,24799,8,GOLD LOAN,"210,000",9,43587,5,6
IB14390,43,FEMALE,BANK MANAGER,MARRIED,6,95247,36035,6,HOUSING,"210,000",7,95247,6,2
IB14392,36,MALE,AIRPORT OFFICER,MARRIED,7,48749,18330,6,SHOPPING,"210,000",5,48749,1,1
IB14395,36,FEMALE,TEACHER,SINGLE,7,43518,null,8,TRAVELLING,"210,000",9,43518,0,0
IB14397,33,MALE,BANK MANAGER,MARRIED,2,70248,22559,5,GOLD LOAN,"210,000",3,70248,6,2
IB14399,50,FEMALE,PROFESSOR,MARRIED,2,84802,21896,5,TRAVELLING,"210,000",5,84802,1,5
IB14400,35,MALE,DENTIST,MARRIED,5,36742,18767,8,COMPUTER SOFTWARES,"210,000",1,36742,8,8
IB14403,28,FEMALE,TEACHER,MARRIED,3,null,19339,8,GOLD LOAN,"210,000",7,null,2,3
IB14406,41,MALE,POLICE,MARRIED,3,33312,21921,5,DINNING,"210,000",2,33312,8,5
IB14408,38,FEMALE,NURSE,MARRIED,6,42490,25775,7,TRAVELLING,"210,000",6,42490,0,4
IB14410,52,MALE,TEACHER,MARRIED,4,75831,27487,5,GOLD LOAN,"210,000",4,75831,6,4
IB14413,36,MALE,SYSTEM MANAGER,MARRIED,5,69163,29339,4,HOME APPLIANCES,"210,000",1,69163,6,5
IB14418,40,FEMALE,TEACHER,MARRIED,6,77627,null,8,TRAVELLING,"210,000",1,77627,4,0
IB14420,43,MALE,SOFTWARE ENGINEER,MARRIED,2,null,23080,7,COMPUTER SOFTWARES,"210,000",4,null,1,8
IB14421,42,FEMALE,DATA ANALYST,MARRIED,4,77671,24112,6,TRAVELLING,"210,000",4,77671,1,6
IB14423,50,MALE,PRODUCT ENGINEER,MARRIED,2,78863,17361,7,DINNING,"210,000",7,78863,1,8
IB14427,55,MALE,POLICE,MARRIED,2,60403,15913,5,SHOPPING,"210,000",7,60403,0,7
IB14430,39,FEMALE,NURSE,MARRIED,5,43323,27877,8,TRAVELLING,"210,000",1,43323,5,4
IB14433,51,MALE,TEACHER,MARRIED,4,42978,29709,5,GOLD LOAN,"210,000",8,42978,9,2
IB14436,24,FEMALE,SYSTEM MANAGER,SINGLE,4,38401,27512,7,RESTAURANTS,"210,000",4,38401,4,2
IB14439,37,MALE,TEACHER,MARRIED,7,79320,19187,6,DINNING,"210,000",6,79320,8,0
IB14440,24,MALE,SOFTWARE ENGINEER,SINGLE,2,31107,21316,7,GOLD LOAN,"210,000",6,31107,1,5
IB14442,32,MALE,DATA ANALYST,MARRIED,6,31948,19502,7,HOUSING,"210,000",3,31948,4,4
IB14444,54,FEMALE,PRODUCT ENGINEER,MARRIED,4,67184,17813,7,HOUSING,"210,000",2,67184,3,1
IB14446,45,MALE,TEACHER,MARRIED,5,null,20185,5,GOLD LOAN,"210,000",7,null,6,0
IB14447,29,FEMALE,ACCOUNT MANAGER,MARRIED,3,55475,28095,4,DINNING,"210,000",3,55475,6,0
IB14449,44,MALE,ASSISTANT PROFESSOR,MARRIED,4,44090,19351,6,TRAVELLING,"210,000",2,44090,8,0
IB14450,29,FEMALE,DOCTOR,MARRIED,5,66138,21787,7,COMPUTER SOFTWARES,"210,000",2,66138,7,4
IB14453,34,MALE,CLERK,MARRIED,7,61207,15955,7,GOLD LOAN,"210,000",4,61207,8,0
IB14457,55,MALE,CIVIL ENGINEER,MARRIED,4,58784,18480,4,AUTOMOBILE,"210,000",4,58784,1,3
IB14459,32,MALE,DOCTOR,MARRIED,4,35472,18340,6,SHOPPING,"210,000",9,35472,0,0
IB14461,54,FEMALE,AIRPORT OFFICER,MARRIED,6,50000,null,5,COMPUTER SOFTWARES,"210,000",8,50000,7,9
IB14463,55,MALE,CLERK,MARRIED,3,51301,17208,4,RESTAURANTS,"210,000",4,51301,4,1
IB14466,24,MALE,PUBLIC WORKS,SINGLE,3,45228,27839,7,SHOPPING,"210,000",8,45228,1,7
IB14467,35,MALE,FIRE DEPARTMENT,MARRIED,4,44522,21803,7,COMPUTER SOFTWARES,"210,000",4,44522,9,4
IB14469,54,MALE,CLERK,MARRIED,3,null,21707,7,RESTAURANTS,"210,000",6,null,9,0
IB14470,29,MALE,NURSE,SINGLE,6,51199,15753,5,COMPUTER SOFTWARES,"210,000",3,51199,3,0
IB14472,44,FEMALE,PRODUCT ENGINEER,MARRIED,2,48613,21617,4,BUILDING,"210,000",5,48613,5,1
IB14472,56,MALE,TEACHER,MARRIED,7,34836,18984,4,ELECTRONICS,"210,000",2,34836,5,5
IB14476,29,MALE,SOFTWARE ENGINEER,SINGLE,5,30454,22210,4,SHOPPING,"210,000",6,30454,7,9
IB14479,34,MALE,BANK MANAGER,MARRIED,5,73070,26306,4,TRAVELLING,"210,000",4,73070,5,1
IB14480,55,MALE,AIRPORT OFFICER,MARRIED,7,56314,19648,7,EDUCATIONAL LOAN,"210,000",2,56314,9,0
IB14483,39,MALE,TEACHER,MARRIED,7,30801,23025,5,AUTOMOBILE,"210,000",1,30801,9,4
IB14486,51,FEMALE,BANK MANAGER,MARRIED,6,57697,15734,5,HOME APPLIANCES,"210,000",1,57697,6,7
IB14489,24,MALE,TEACHER,SINGLE,5,74609,20444,4,RESTAURANTS,"210,000",2,74609,0,3
IB14490,37,FEMALE,SYSTEM MANAGER,MARRIED,2,71477,28652,8,SHOPPING,"210,000",8,71477,1,5
IB14491,24,MALE,TEACHER,SINGLE,2,77923,null,5,TRAVELLING,"210,000",5,77923,2,8
IB14493,24,FEMALE,SOFTWARE ENGINEER,SINGLE,3,null,29521,7,GOLD LOAN,"210,000",7,null,6,9
IB14495,44,MALE,DATA ANALYST,MARRIED,3,56036,16416,7,AUTOMOBILE,"210,000",4,56036,2,6

Databricks visualization. Run in Databricks to view.

In [0]:
%sql
describe loan_analysiss

col_name,data_type,comment
Customer_ID,string,null
Age,int,null
Gender,string,null
Occupation,string,null
Marital Status,string,null
Family Size,int,null
Income,int,null
Expenditure,int,null
Use Frequency,int,null
Loan Category,string,null
Debt,string,null
Overdue,int,null
Loan,int,null
Returned Cheque,int,null
Dishonour of Bill,int,null

In [0]:
%sql
select gender , sum(loan) from loan_analysiss
group by Gender

gender,sum(loan)
MALE,16048108
FEMALE,15934774

Databricks visualization. Run in Databricks to view.

In [0]:
%sql
select distinct Occupation from loan_analysiss

Occupation
CIVIL ENGINEER
FIRE DEPARTMENT
ACCOUNTANT
BANK MANAGER
SYSTEM OFFICER
NUTRITION
DIETICIAN
CLERK
SOFTWARE ENGINEER
AGRICULTURAL ENGINEER
ASSISTANT MANAGER
TEACHER
ASSISTANT PROFESSOR
SYSTEM ENGINEER
CHARTERED APPRAISER
NAVY
POLICE
BUSINESS
FARMER
DRIVER
ELECTRICIAN
DATA ENGINEER
EXECUTIVE
DENTIST
SYSTEM MANAGER
PUBLIC WORKS
TECHNICIAN
ARMY
AIRPORT OFFICER
PILOT
MANAGER
ACCOUNT MANAGER
STORE KEEPER
DOCTOR
PRODUCT ENGINEER
CORPORATE OFFICER
PROFESSOR
NURSE
DATA ANALYST

In [0]:
%sql
select Occupation, sum(Loan) from loan_analysiss
group by Occupation 
order by 2 desc
limit 15

Occupation,sum(Loan)
ACCOUNT MANAGER,3390974
TEACHER,3168764
BANK MANAGER,2396966
CLERK,1844907
SOFTWARE ENGINEER,1833234
DOCTOR,1808363
DRIVER,1160115
PILOT,1147651
NAVY,1139055
AIRPORT OFFICER,962915
BUSINESS,906921
POLICE,882898
DIETICIAN,871190
CHARTERED APPRAISER,841024
FIRE DEPARTMENT,664295

Databricks visualization. Run in Databricks to view.

In [0]:
%sql
select distinct 'Loan Category'  from loan_analysiss
limit 10

Loan Category
Loan Category

In [0]:
%python
import pyspark.sql.functions as F

# Read the loan_analysiss table into a DataFrame
loan_df = spark.read.table("loan_analysiss")

# Group by Loan Category, calculate the sum of Loan, and order by descending sum
grouped_df = loan_df.groupBy("Loan Category").agg(F.sum("Loan").alias("Total_Loan")).orderBy(F.desc("Total_Loan"))

# Display all rows of the grouped DataFrame
display(grouped_df)

Loan Category,Total_Loan
GOLD LOAN,5171197
HOUSING,4633148
AUTOMOBILE,3892281
COMPUTER SOFTWARES,3628170
TRAVELLING,3021879
RESTAURANTS,2153923
BUSINESS,1685917
SHOPPING,1614923
RESTAURANT,1292942
EDUCATIONAL LOAN,1054980
HOME APPLIANCES,824536
ELECTRONICS,766198
DINNING,743793
AGRICULTURE,724472
BUILDING,418201
BOOK STORES,356322

Databricks visualization. Run in Databricks to view.

In [0]:
%python
# Read the loan_analysiss table into a DataFrame
loan_df = spark.read.table("loan_analysiss")

# Group by Marital Status, calculate the sum of Loan, and order by Marital Status
grouped_df = loan_df.groupBy("Marital Status").agg(F.sum("Loan")).orderBy("Marital Status")

# Display all rows of the grouped DataFrame
display(grouped_df)

Marital Status,sum(Loan)
MARRIED,23226313
SINGLE,8756569

Databricks visualization. Run in Databricks to view.